services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./server/src:/app/src
      - ./server/nodemon.json:/app/nodemon.json
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: npm run dev
